---
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
    run-tests:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - run: |
            make install
            make test
