---
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
    run-tests:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - run: |
            python -m pip install poetry
            make install
            make test
            make build

    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/pystream-collections
      permissions:
        id-token: write
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
